# Generated by Django 4.2.20 on 2025-03-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Singer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("singer", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("album", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=30)),
                ("cover_image", models.URLField(blank=True)),
                ("lyric", models.TextField()),
                ("genre", models.CharField(max_length=15)),
                ("date", models.DateField()),
                ("good", models.IntegerField()),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.singer"
                    ),
                ),
            ],
        ),
    ]
